### ISSUE TITLE
Feature request: Homebrew support

### ISSUE THREAD

**Issue by noraworld** [mayankk2308/set-egpu#21]
I would be happy if you could support Homebrew so that we can install set-eGPU via Homebrew.

```sh
$ brew install set-egpu
```

**Comment by mayankk2308** [comment]
@noraworld Self-updating scripts such as `set-eGPU` are [generally frowned upon in the brew world](https://docs.brew.sh/Acceptable-Formulae).

Initially I decided against it because a lot of users are not software developers and would not have/require `brew` - and I don't want people installing more than what they need. The self-updating nature of my scripts just doesn't align with the goals of `brew`. The prospect of adding my scripts to `brew` has been tempting, but I dislike having that conflict-of-concerns with respect to updates. For now, I will not be adding `brew` support, but will keep you suggestion in mind.

**Comment by noraworld** [comment]
I understood about that. Thank you for your reply.
