### ISSUE TITLE
Mojave eGPU Preference?

### ISSUE THREAD

**Issue by latenitefilms** [mayankk2308/set-egpu#6]
@mayankk2308 - Have you worked out where macOS is saving the eGPU application preference in Mojave yet?

**Comment by mayankk2308** [comment]
It’s doing something really different. I have an alternate technique which I may implement soon (it’s not pretty but would get the job done). I will investigate further.

**Comment by latenitefilms** [comment]
@mayankk2308 - Awesome, thanks! I realise that it's now really easy for end-users to just right click on an application, "Get Info", then toggle "Prefer External GPU" - however I'd love a way to be able to programatically detect whether or not an application has this option set. I can't really see anything online in regards to where this preference is saved, so very intrigued to see what you come up with - as I've tried digging around, but haven't come across the secret sauce yet. Thanks again!

**Comment by mayankk2308** [comment]
@latenitefilms Quick update on my investigation: As of Mojave, Apple seems to have simply removed any obvious command-line way of setting eGPU preferences. The one technique that did work was to edit the application's Info.plist file, but this has huge ramifications:
- Invalidates code signature
- If done on Mojave, could prevent system from booting
- On Mojave SIP extends to 3rd-party apps as well so..

So essentially it is up to developers to provide the key in their plist bundles. The last trick up my sleeve is an **AppleScript** that can invoke the appropriate Get Info window, check the preference if the checkbox is present, and then close the window (have built it for a single app, just need to scale it which is easy). For multiple apps, you can imagine the drama on-screen. This would also require the eGPU to be plugged in (otherwise the checkbox won't show up). Overall it doesn't seem worth it to investigate further.
